const express = require('express');
const router = express.Router();
const { authenticate, requireRole } = require('../middleware/auth.middleware');
const prisma = require('../config/prisma');
const { generatePONumber, calculateVAT, roundDecimal, paginate, paginatedResponse } = require('../utils/helpers');
const { createAuditLog } = require('../middleware/audit.middleware');

router.use(authenticate);

router.get('/', async (req, res) => {
  try {
    const { page, limit, status, supplierId, isAutoGenerated } = req.query;
    const { take, skip } = paginate(page, limit);
    const where = { tenantId: req.tenantId };
    if (status) where.status = status;
    if (supplierId) where.supplierId = supplierId;
    if (isAutoGenerated !== undefined) where.isAutoGenerated = isAutoGenerated === 'true';
    const [data, total] = await Promise.all([
      prisma.purchaseOrder.findMany({
        where, take, skip, orderBy: { createdAt: 'desc' },
        include: { supplier: { select: { id: true, name: true } }, lines: { include: { product: { select: { id: true, name: true, sku: true } } } } },
      }),
      prisma.purchaseOrder.count({ where }),
    ]);
    res.json(paginatedResponse(data, total, page, limit));
  } catch (e) { res.status(500).json({ error: 'Failed to fetch purchase orders' }); }
});

router.get('/:id', async (req, res) => {
  try {
    const po = await prisma.purchaseOrder.findFirst({
      where: { id: req.params.id, tenantId: req.tenantId },
      include: { supplier: true, lines: { include: { product: true } } },
    });
    if (!po) return res.status(404).json({ error: 'Purchase order not found' });
    res.json({ data: po });
  } catch (e) { res.status(500).json({ error: 'Failed to fetch purchase order' }); }
});

router.post('/', requireRole('OWNER','ADMIN','ACCOUNTANT','WAREHOUSE'), async (req, res) => {
  try {
    const { supplierId, expectedDate, currency, exchangeRate, lines, notes } = req.body;
    if (!supplierId || !lines?.length) return res.status(400).json({ error: 'Supplier and line items are required' });
    const supplier = await prisma.supplier.findFirst({ where: { id: supplierId, tenantId: req.tenantId } });
    if (!supplier) return res.status(404).json({ error: 'Supplier not found' });

    const count = await prisma.purchaseOrder.count({ where: { tenantId: req.tenantId } });
    const poNumber = generatePONumber('PO', count + 1);

    let subtotal = 0, vatAmount = 0;
    const processedLines = lines.map((l) => {
      const lineSubtotal = roundDecimal(l.quantity * l.unitPrice);
      const vat = calculateVAT(lineSubtotal, l.vatRate ?? 0.075);
      subtotal += lineSubtotal;
      vatAmount += vat;
      return { ...l, vatRate: l.vatRate ?? 0.075, vatAmount: vat, lineTotal: roundDecimal(lineSubtotal + vat) };
    });

    const po = await prisma.purchaseOrder.create({
      data: {
        tenantId: req.tenantId, supplierId, poNumber,
        issueDate: new Date(),
        expectedDate: expectedDate ? new Date(expectedDate) : null,
        currency: currency || 'NGN',
        exchangeRate: exchangeRate || 1,
        subtotal: roundDecimal(subtotal),
        vatAmount: roundDecimal(vatAmount),
        whtAmount: 0,
        totalAmount: roundDecimal(subtotal + vatAmount),
        notes, createdById: req.user.id,
        lines: { create: processedLines },
      },
      include: { supplier: true, lines: true },
    });
    await createAuditLog({ tenantId: req.tenantId, userId: req.user.id, action: 'CREATE', resource: 'PurchaseOrder', resourceId: po.id, req });
    res.status(201).json({ data: po });
  } catch (e) { res.status(500).json({ error: 'Failed to create purchase order' }); }
});

router.put('/:id/status', requireRole('OWNER','ADMIN','ACCOUNTANT','WAREHOUSE'), async (req, res) => {
  try {
    const { status } = req.body;
    const po = await prisma.purchaseOrder.findFirst({ where: { id: req.params.id, tenantId: req.tenantId } });
    if (!po) return res.status(404).json({ error: 'Purchase order not found' });
    const updated = await prisma.purchaseOrder.update({ where: { id: po.id }, data: { status } });
    res.json({ data: updated });
  } catch (e) { res.status(500).json({ error: 'Failed to update purchase order' }); }
});

router.post('/:id/receive', requireRole('OWNER','ADMIN','WAREHOUSE'), async (req, res) => {
  try {
    const { warehouseId, receivedLines } = req.body;
    if (!warehouseId) return res.status(400).json({ error: 'Warehouse required' });
    const po = await prisma.purchaseOrder.findFirst({ where: { id: req.params.id, tenantId: req.tenantId }, include: { lines: true } });
    if (!po) return res.status(404).json({ error: 'PO not found' });

    await prisma.$transaction(async (tx) => {
      for (const recv of receivedLines) {
        const line = po.lines.find((l) => l.id === recv.lineId);
        if (!line) continue;
        await tx.purchaseOrderLine.update({ where: { id: line.id }, data: { receivedQty: { increment: recv.quantity } } });
        await tx.stockLevel.upsert({
          where: { productId_warehouseId: { productId: line.productId, warehouseId } },
          update: { quantity: { increment: recv.quantity } },
          create: { tenantId: req.tenantId, productId: line.productId, warehouseId, quantity: recv.quantity },
        });
        await tx.stockMovement.create({
          data: { tenantId: req.tenantId, productId: line.productId, warehouseId, type: 'PURCHASE_RECEIPT', quantity: recv.quantity, sourceId: po.id, sourceType: 'PurchaseOrder', createdById: req.user.id },
        });
      }
      const allLines = await tx.purchaseOrderLine.findMany({ where: { poId: po.id } });
      const fullyReceived = allLines.every((l) => l.receivedQty >= l.quantity);
      await tx.purchaseOrder.update({ where: { id: po.id }, data: { status: fullyReceived ? 'RECEIVED' : 'PARTIAL' } });
    });
    res.json({ message: 'Goods received and stock updated' });
  } catch (e) { res.status(500).json({ error: 'Failed to receive goods' }); }
});

module.exports = router;
